---
- name: lancement des mises a jour
  yum:  name=* state=latest

- name: install epel-release
  yum:  name=epel-release state=present

- name: Install packages
  yum: name={{ item }} state=latest
  with_items:
   - libselinux-python 
   - python34-setuptools
   - python34
   - git

- name: reload ansible facts
  setup: 

- name:  Get pip3
  shell: wget https //bootstrap.pypa.io/get-pip.py

- name:  Install pip3
  shell: python3 get-pip.py

- name:  creation directorie de travail 
  file: path=/home/dev/ state=directory

- name: copy python librairies configuration files 
  copy: src=requirements.txt  dest=/home/dev/requirements.txt

- name:  installation des librairies flask
  shell:  pip3 install -r /home/dev/requirements.txt

- name:  creation directorie static de travail
  file: path=/home/dev/static state=directory

- name:  creation directorie templates de travail
  file: path=/home/dev/templates state=directory

- name: copy main file  
  copy: src=hello.py  dest=/home/dev/hello.py

- name: copy directory
  copy: src={{ item }} dest=/home/dev/static 
  with_fileglob:
    - static/*

- name: copy directory
  copy: src={{ item }} dest=/home/dev/templates 
  with_fileglob:
    - templates/*

